
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-surfshark}
      - VPN_TYPE=${VPN_TYPE:-wireguard}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES:-10.14.0.2/16}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Estonia}
    ports:
      - "${QB_WEBUI_PORT:-8880}:8880/tcp"
      - "${TORRENT_PORT:-6881}:6881/tcp"
      - "${TORRENT_PORT:-6881}:6881/udp"
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped
    networks:
      - torrent_network

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - WEBUI_PORT=${QB_WEBUI_PORT:-8880}
      - TORRENTING_PORT=${TORRENT_PORT:-6881}
    volumes:
      - ${DATA_DIR:-./data}/appdata:/config
      - ${DOWNLOAD_DIR:-./data}/downloads:/downloads
    restart: unless-stopped
    depends_on:
      - gluetun

  anime_watchlist:
    build: ./app
    container_name: anime_watchlist
    environment:
      - QBITTORRENT_HOST=gluetun
      - QBITTORRENT_PORT=${QB_WEBUI_PORT:-8880}
      - QBITTORRENT_USERNAME=${QB_USERNAME:-admin}
      - QBITTORRENT_PASSWORD=${QB_PASSWORD:-adminadmin}
      - FLASK_PORT=${FLASK_PORT:-5000}
      - TZ=${TZ:-Etc/UTC}
    volumes:
      - ${DATA_DIR:-./data}/anime_db:/app/data
    ports:
      - "${FLASK_PORT:-5000}:5000"
    restart: unless-stopped
    depends_on:
      - qbittorrent
    networks:
      - torrent_network

networks:
  torrent_network:
    driver: bridge