services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add: [ NET_ADMIN ]
    environment:
      - VPN_SERVICE_PROVIDER=${VPN_SERVICE_PROVIDER:-surfshark}
      - VPN_TYPE=${VPN_TYPE:-wireguard}
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES:-10.14.0.2/16}
      - SERVER_COUNTRIES=${SERVER_COUNTRIES:-Estonia}
    ports:
      - "${QB_WEBUI_PORT:-8880}:8880/tcp"
      - "${TORRENT_PORT:-6881}:6881/tcp"
      - "${TORRENT_PORT:-6881}:6881/udp"
    volumes:
      - ./gluetun:/gluetun
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "https://google.com"]
      interval: 10s
      timeout: 5s
      retries: 6
    networks:
      gluetun_net:
        aliases:
          - vpn-gateway

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: "service:gluetun"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Etc/UTC}
      - WEBUI_PORT=${QB_WEBUI_PORT:-8880}
      - TORRENTING_PORT=${TORRENT_PORT:-6881}
    volumes:
      - ${DATA_DIR:-./data}/appdata:/config
      - ${DOWNLOAD_DIR:-./data}/downloads:/downloads
    depends_on:
       gluetun:
        condition: service_healthy
    restart: unless-stopped

  anime_watchlist:
    build: ./app
    container_name: anime_watchlist
    networks:
      - gluetun_net
    environment:
      - QBITTORRENT_HOST=vpn-gateway
      - QBITTORRENT_PORT=${QB_WEBUI_PORT:-8880}
      - QBITTORRENT_USERNAME=${QB_USERNAME:-admin}
      - QBITTORRENT_PASSWORD=${QB_PASSWORD:-adminadmin}
      - FLASK_PORT=${FLASK_PORT:-5000}
      - TZ=${TZ:-Etc/UTC}
      # optional scheduler globals:
      # - SCHEDULE_INTERVAL=1
      # - SCHEDULE_UNIT=hour
    volumes:
      - ${DATA_DIR:-./data}/anime_db:/app/data
    ports:
      - "5000:5000"       # Flask exposed via Gluetun
    depends_on:
       gluetun:
        condition: service_healthy
    restart: unless-stopped

networks:
  gluetun_net:
    driver: bridge